name: "Code Quality Check"

on: push

jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno lint
